syntax = "proto3";

package gamepb.activitypb;

import "corepb.proto";

service ActivityService {
  rpc List(ListRequest) returns (ListReply);
  rpc GetGroup(GetGroupRequest) returns (GetGroupReply);
}

message ListRequest {}

message GetGroupRequest {
  int64 id = 1;
  string uid = 2;
}

message RandomShopItem {
  int32 id = 1;
  string name = 2;
  corepb.Item item = 4;
  corepb.Item cost = 5;
  int32 stock_count = 6;
  int32 bought_count = 7;
  bool special = 8;
}

message RandomShopInfo {
  repeated RandomShopItem items = 1;
  int64 next_refresh_time = 2;
  int32 manual_refresh_cost = 3;
  int32 manual_refresh_currency_id = 4;
  int32 manual_refresh_extra_value = 5;
  int32 max_manual_refresh_count = 6;
  int32 manual_refresh_used_count = 7;
}

message ExchangeShopItem {
  int32 id = 1;
  corepb.Item item = 2;
  corepb.Item cost = 3;
  int32 status = 4;
  bool owned = 5;
  int32 sort = 6;
  string name = 7;
  string extra = 8;
}

message ExchangeShopInfo {
  repeated ExchangeShopItem items = 1;
}

message DrawPoolItem {
  int32 id = 1;
  int32 rarity = 2;
  corepb.Item item = 3;
  int32 flag = 4;
  string probability = 6;
}

message DrawInfo {
  int32 free_remaining_count = 1;
  int32 max_free_count = 2;
  int32 paid_remaining_count = 3;
  int32 max_paid_count = 4;
  int32 paid_currency_id = 5;
  int32 paid_price = 6;
  int32 fallback_price = 7;
  repeated DrawPoolItem rewards = 8;
}

message ActivityInfo {
  int64 id = 1;
  int64 parent_id = 2;
  int32 type = 3;
  string title = 4;
  string payload = 5;
  int64 start_time = 6;
  int64 end_time = 7;
  int32 sort = 8;
  bool visible = 20;
  int32 status = 21;
  bool enabled = 22;
  RandomShopInfo random_shop = 101;
  ExchangeShopInfo exchange_shop = 102;
  DrawInfo draw_info = 105;
}

message ActivityNode {
  ActivityInfo activity = 1;
  repeated ActivityNode children = 2;
  RandomShopInfo random_shop = 101;
  ExchangeShopInfo exchange_shop = 102;
  DrawInfo draw_info = 105;
}

message ListReply {
  repeated ActivityInfo activities = 1;
}

message GetGroupReply {
  ActivityNode group = 1;
}
